config/routes.rb
Rails.application.routes.draw do
  resources :job_postings
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :job_postings
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all.paginate(page: params[:page], per_page: 3).order(name: :desc)
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: [:show, :edit, :update, :destroy]

  # GET /job_postings
  # GET /job_postings.json
  def index
      if params[:mode] == "title"
        @job_postings = JobPosting.all.paginate(page: params[:page], per_page: 3).order(title: :asc)
      elsif params[:mode] == "single"
        @job_postings = JobPosting.where(department_id: params[:id]).paginate(page: params[:page], per_page: 3)
      else
        @job_postings = JobPosting.joins(:department).paginate(page: params[:page], per_page: 3).order("departments.name")
      end
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1
  # PATCH/PUT /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting.destroy
    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: 'Job posting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_posting_params
      params.require(:job_posting).permit(:title, :url, :content, :entry_id, :job_published_at, :job_updated_at, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/views/departments/_form.html.haml
= form_with(model: department, local: true) do |form|
  - if department.errors.any?
    #error_explanation
      %h2
        = pluralize(department.errors.count, "error")
        prohibited this department from being saved:
      %ul
        - department.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/departments/edit.html.haml
%h1 Editing Department
= render 'form', department: @department
= link_to 'Show', @department
|
= link_to 'Back', departments_path

app/views/departments/index.html.haml
%p#notice= notice
%h1 Departments
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @departments.each do |department|
      %tr
        %td= department.name
        %td= link_to 'Show | ', department
        %td= link_to 'Edit | ', edit_department_path(department)
        %td= link_to 'Destroy | ', department, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'View Job Listings', "/job_postings?mode=single&id=#{department.id}"
%br/
= will_paginate @departments
= link_to 'New Department', new_department_path
%br/
= link_to 'All Job Listings', '/job_postings?mode=title'

app/views/departments/new.html.haml
%h1 New Department
= render 'form', department: @department
= link_to 'Back', departments_path

app/views/departments/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @department.name
= link_to 'Edit', edit_department_path(@department)
|
= link_to 'Back', departments_path

app/views/job_postings/_form.html.haml
= form_with(model: job_posting, local: true) do |form|
  - if job_posting.errors.any?
    #error_explanation
      %h2
        = pluralize(job_posting.errors.count, "error")
        prohibited this job_posting from being saved:
      %ul
        - job_posting.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :url
    = form.text_field :url
  .field
    = form.label :content
    = form.text_area :content
  .field
    = form.label :entry_id
    = form.number_field :entry_id
  .field
    = form.label :job_published_at
    = form.datetime_select :job_published_at
  .field
    = form.label :job_updated_at
    = form.datetime_select :job_updated_at
  .field
    = form.label :department_id
    = form.text_field :department_id
  .actions
    = form.submit

app/views/job_postings/edit.html.haml
%h1 Editing Job Posting
= render 'form', job_posting: @job_posting
= link_to 'Show', @job_posting
|
= link_to 'Back', job_postings_path

app/views/job_postings/index.html.haml
%p#notice= notice
%h1 Job Postings
%table.table.table-hover.table-striped
  %thead
    %tr
      %th Title
      %th Url
      %th Content
      %th Department
      %th{:colspan => "3"}
  %tbody
    - @job_postings.each do |job_posting|
      %tr
        %td= job_posting.title
        %td= job_posting.url
        %td= truncate job_posting.content
        %td= job_posting.department.name
        %td= link_to 'Show', job_posting
        %td= link_to 'Edit', edit_job_posting_path(job_posting)
        %td= link_to 'Destroy', job_posting, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= will_paginate @departments
= link_to 'New Job Posting', new_job_posting_path
%br/
= link_to 'Job Listings by Title | ', '/job_postings?mode=title'
= link_to 'Job Listings by Department', '/job_postings?mode=department'
%br/
= link_to 'Departments', '/departments'

app/views/job_postings/new.html.haml
%h1 New Job Posting
= render 'form', job_posting: @job_posting
= link_to 'Back', job_postings_path

app/views/job_postings/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @job_posting.title
%p
  %strong Url:
  = @job_posting.url
%p
  %strong Content:
  = @job_posting.content
%p
  %strong Entry:
  = @job_posting.entry_id
%p
  %strong Job published at:
  = @job_posting.job_published_at
%p
  %strong Job updated at:
  = @job_posting.job_updated_at
%p
  %strong Department:
  = @job_posting.department
= link_to 'Edit', edit_job_posting_path(@job_posting)
|
= link_to 'Back', job_postings_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OsuJobsPhae
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield